# Generated by Django 4.2.1 on 2023-06-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
